iommu: samsung: drop unused functions to avoid compiler error
With W=1, clang complains:
    drivers/iommu/samsung-iommu.c:91:20: error: unused function '__sysmmu_has_capa1' [-Werror,-Wunused-function]
       91 | static inline bool __sysmmu_has_capa1(struct sysmmu_drvdata *data)
          |                    ^~~~~~~~~~~~~~~~~~
    drivers/iommu/samsung-iommu.c:96:19: error: unused function '__sysmmu_get_capa_type' [-Werror,-Wunused-function]
       96 | static inline u32 __sysmmu_get_capa_type(struct sysmmu_drvdata *data)
          |                   ^~~~~~~~~~~~~~~~~~~~~~

Drop these unused functions.

Test: TH
Fixes: 68d70170d2c4 ("iommu/samsung: remove TLB way dedication which is deprecated")
Fixes: 0caee750fa3f ("iommu/samsung: remove TLB way dedication which is deprecated")
Bug: 423391571
Change-Id: I2b6cef79debc98dfecee1fef57f3bf45979831e7
Signed-off-by: André Draszik <draszik@google.com>