misc: sbb-mux: replace of_device.h with excplicit includes (v6.8 compatibility)
Linux commit [1] has removed some old, long-standing circular includes
in of_device.h and of_platform.h which causes this OOT pixel driver to
fail compilation:
    ../soc/gs/drivers/misc/sbb-mux/sbb-mux.c:466:6: error: call to undeclared function 'of_property_read_string_index'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      466 |         if (of_property_read_string_index(platform_dev->dev.of_node,
          |             ^
    .../soc/gs/drivers/misc/sbb-mux/sbb-mux.c:580:3: error: call to undeclared function 'of_property_count_strings'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      580 |                 of_property_count_strings(dev->dev.of_node, "gpio_names");
          |                 ^
    2 errors generated.

The DT of_device.h and of_platform.h date back to the separate
of_platform_bus_type before it as merged into the regular platform bus.
As part of that merge prepping Arm DT support 13 years ago, they
"temporarily" include each other. They also include platform_device.h
and of.h.

of_device.h isn't needed, but of.h which was included implicitly is.
Make it explicit.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ef175b29a242
          ("of: Stop circularly including of_device.h and of_platform.h")
Test: TH
Bug: 331381449
Change-Id: I0d6af09582a82e9d01fdd9b07963cec7c7d6ba2b
Signed-off-by: André Draszik <draszik@google.com>