iommu: samsung: drop unused variable 'fwspec' in samsung_sysmmu_of_xlate()
With W=1, Clang and gcc complain correctly:

    drivers/iommu/samsung-iommu.c:953:23: error: variable 'fwspec' set but not used [-Werror,-Wunused-but-set-variable]
      953 |         struct iommu_fwspec *fwspec;
          |                              ^

Drop the unused assignment and variable.

Test: TH
Fixes: f562c5d6038d ("GKI: iommu/samsung: Port samsung iommu to mainline")
Bug: 423391571
Change-Id: I7aebf7667c561b599f3857a485e809846a88c0b4
Signed-off-by: André Draszik <draszik@google.com>