power: IIO: fix -Wmissing-prototypes errors
Mark some functions in this module as static in order to fix the
Wmissing-prototypes errors reported such as:

  private/google-modules/soc/gs/drivers/iio/power/odpm.c:289:5: \
  error: no previous prototype for function 'odpm_configure_chip' [-Werror,-Wmissing-prototypes]
  289 | int odpm_configure_chip(struct odpm_info *info)
      |     ^

  private/google-modules/soc/gs/drivers/iio/power/odpm.c:289:1: \
  note: declare 'static' if the function is not intended to be used outside of this translation unit
  289 | int odpm_configure_chip(struct odpm_info *info)
      | ^
      | static

Note this patch also fixes a KP when loading this module after v6.19
updates to objtool in GKI. See more details in the bug.

Bug: 470420961
Change-Id: I603f96be0b1306f737640cbcaa7b59313774fd46
Signed-off-by: Carlos Llamas <cmllamas@google.com>