iommu: constify of_phandle_args in of_xlate() (v6.9 compatibility)
Linux commit [1] has const'ified struct iommu_ops::of_xlate(). This
causes compilation of OOT Pixel iommu drivers to fail:

    .../soc/gs/drivers/iommu/samsung-iommu.c:1245:15: error: incompatible function pointer types initializing 'int (*)(struct device *, const struct of_phandle_args *)' with an expression of type 'int (struct device *, struct of_phandle_args *)' [-Wincompatible-function-pointer-types]
     1245 |         .of_xlate               = samsung_sysmmu_of_xlate,
          |                                   ^~~~~~~~~~~~~~~~~~~~~~~

Update the code accordingly.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b42a905b6aad
          ("iommu: constify of_phandle_args in xlate")
Test: TH
Bug: 333509553
Change-Id: Ic6e04665d529b30cc47ca128b03d4df03228c152
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit fae223a58641b4a06270e1add5f0b025283110a4)
Signed-off-by: Will McVicker <willmcvicker@google.com>