tcpci_max77759.c: fix -Wstringop-overflow warning (strncat()) (v6.8 compatibility)
When compiling with gcc, it righteously complains about suspicious use
of strncat() here:

drivers/usb/typec/tcpm/google/tcpci_max77759.c: In function ‘compliance_warnings_to_buffer’:
drivers/usb/typec/tcpm/google/tcpci_max77759.c:770:17: error: ‘strncat’ specified bound 7 equals source length [-Werror=stringop-overflow=]
  770 |                 strncat(buf, "other, ", strlen("other, "));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:772:17: error: ‘strncat’ specified bound 17 equals source length [-Werror=stringop-overflow=]
  772 |                 strncat(buf, "debug-accessory, ", strlen("debug-accessory, "));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:774:17: error: ‘strncat’ specified bound 6 equals source length [-Werror=stringop-overflow=]
  774 |                 strncat(buf, "bc12, ", strlen("bc12, "));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:776:17: error: ‘strncat’ specified bound 12 equals source length [-Werror=stringop-overflow=]
  776 |                 strncat(buf, "missing_rp, ", strlen("missing_rp, "));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:778:17: error: ‘strncat’ specified bound 21 equals source length [-Werror=stringop-overflow=]
  778 |                 strncat(buf, "input_power_limited, ", strlen("input_power_limited, "));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:779:9: error: ‘strncat’ specified bound 1 equals source length [-Werror=stringop-overflow=]
  779 |         strncat(buf, "]", strlen("]"));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The expected use of strncat() is to constrain the copy to the space
remaining in the destination to avoid buffer overflow. Passing the
length or size of the source buffer as the bound defeats the function's
intended purpose and makes it behave the same as strcat().

Looking at it, we can do better and use scnprintf() instead. This has
several benefits:
* the start byte in the destination doesn't have to be re-evaluated
  constantly (as is done in each call to strncat() otherwise)
* it's easy to check for overflow
* we don't needlessly fill the whole buf with PAGE_SIZE '\0'
  (snprintf() guarantees to NULL-terminate the destination)
* it always returns the number of bytes written to the destination,
  which mean we don't need an extra pass through strnlen()

Test: TH
Bug: 327137249
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from https://partner-android-review.googlesource.com/q/commit:7c55d151d9d8512f24b85e830d5396f81c22de2d)
Merged-In: Ia3a6a080175c6ade11bc9b2ba5d7a86c8ed1be72
Change-Id: Ia3a6a080175c6ade11bc9b2ba5d7a86c8ed1be72
Signed-off-by: Will McVicker <willmcvicker@google.com>