soc: google: dss: use for_each_process_thread() (prepare for v6.7)
Linux commit [1] has removed struct task_struct::thread_group and this
causes this OOT pixel driver to fail compilation:

    .../gs/drivers/soc/google/debug/debug-snapshot-utils.c:316:27: error: no member named 'thread_group' in 'struct task_struct'; did you mean 'thread_node'?
            return container_of(tsk->thread_group.next, struct task_struct, thread_group);
                                     ^~~~~~~~~~~~
                                     thread_node
    etc.

We can simply use the provided kernel APIs. This will avoid breakage,
and greatly simplify the code.
Note: I do not know if there was a specific reason to have this all
open-coded previously.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8e1f385104ac
    ("kill task_struct->thread_group")

Bug: 317037874
Test: TH
Change-Id: I6a8f2814b8b40cad24d23c2c1b190791cdb5de32
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 264876c9a08f17fc6a66023e229794771d5040d7)