drivers: devfreq: fix compilation for CONFIG_ECT=n
With CONFIG_ECT disabled, this file doesn't compile:

    In file included from .../display/samsung/exynos_drm_dpp.c:34:
    ../soc/gs/include/soc/google/exynos-devfreq.h:267:1: error: expected identifier or '('
      267 | {
          | ^
    1 error generated.

Update the empty implementation to allow compilation.

Test: TH, locally compile without CONFIG_ECT
Fixes: d90c8fd3bab0 ("drivers: devfreq: add memlat devfreq driver")
Bug: 423391571
Change-Id: I075aa7f3999d026b5e06f3ace3d301893592730a
Signed-off-by: André Draszik <draszik@google.com>