pci / dwc3: s/host_init/init (v6.8 compatibility)
Linux commit [1] has dropped the 'host_' prefix from all 'struct
dw_pcie_host_ops' members, which causes this driver to fail
compilation:

    .../gs/drivers/pci/controller/dwc/pcie-exynos-rc.c:2839:3: error: field designator 'host_init' does not refer to any field in type 'struct dw_pcie_host_ops'; did you mean 'post_init'?
     2839 |         .host_init = exynos_pcie_rc_init,
          |          ^~~~~~~~~
          |          post_init
    .../common/drivers/pci/controller/dwc/pcie-designware.h:305:9: note: 'post_init' declared here
      305 |         void (*post_init)(struct dw_pcie_rp *pp);
          |                ^
    .../gs/drivers/pci/controller/dwc/pcie-exynos-rc.c:2839:15: error: incompatible function pointer types initializing 'void (*)(struct dw_pcie_rp *)' with an expression of type 'int (struct dw_pcie_rp *)' [-Wincompatible-function-pointer-types]
     2839 |         .host_init = exynos_pcie_rc_init,
          |                      ^~~~~~~~~~~~~~~~~~~
    2 errors generated.

Update the code accordingly.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=aea370b2aec9
      ("PCI: dwc: Drop host prefix from struct dw_pcie_host_ops members")
Test: TH
Bug: 331392809
Change-Id: I76750d31d22aba60aa6562acff8821673ed29635
Signed-off-by: André Draszik <draszik@google.com>