scsi: ufs: exynos: move 4K alignment code here (v6.7 compatibility)
Linux commit [1] has moved all logic around 4K alignment directly into
the Exynos driver with the following justification:
    The DMA alignment for the Exynos controller follows directly from
    the PRDT segment size configured in ufs-exynos.c. Hence, move the
    DMA alignment code into the Exynos driver source code.

The UFSHCD_QUIRK_4KB_DMA_ALIGNMENT flag is therefore gone and this
driver here fails compilation:

.../drivers/scsi/ufs/ufs-exynos.c:459:4: error: use of undeclared identifier 'UFSHCD_QUIRK_4KB_DMA_ALIGNMENT'
                        UFSHCD_QUIRK_4KB_DMA_ALIGNMENT;
                        ^
1 error generated.

Update the driver similar to the upstream change.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=858231bdb223
    ("scsi: ufs: core: Move the 4K alignment code into the Exynos driver")

Fixes: 858231bdb223 ("scsi: ufs: core: Move the 4K alignment code into the Exynos driver")
Bug: 316554708
Test: TH
Change-Id: Ia88e612be1ddf60ea2cdefed6a5425d82488e683
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit ac4fcd8aed1a40b1e55b1ccd55a94ff58e748658)