iommu: samsung: address Werror=missing-declarations (samsung_sysmmu_unmap_pages)
gcc correctly complains:
      CC [M]  samsung-iommu.o
    samsung-iommu.c:675:8: error: no previous declaration for ‘samsung_sysmmu_unmap_pages’ [-Werror=missing-declarations]
      675 | size_t samsung_sysmmu_unmap_pages(struct iommu_domain *dom, unsigned long iova_org,
          |        ^~~~~~~~~~~~~~~~~~~~~~~~~~

Mark the function as static as it is not used anywhere outside this
file to address the warning.

Test: TH
Fixes: b0048f49d474 ("iommu/samsung: optimize PTE flush")
Bug: 423391571
Change-Id: Id9b551d75736839045d377e1d87449ff2c6a377d
Signed-off-by: André Draszik <draszik@google.com>