drivers: thermal: tmu: struct thermal_zone_device::ops is not a pointer (v6.9 compatibility)
Linux commit [1] has changed struct thermal_zone_device::ops to not be
a pointer anymore. This causes this driver to fail compilation:

    .../soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:2987:11: error: member reference type 'struct thermal_zone_device_ops' is not a pointer; did you mean to use '.'?
     2987 |                         tz->ops->set_trip_temp(tz, i, temperature  * MCELSIUS);
          |                         ~~~~~~~^~
          |                                .
    .../soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:3050:11: error: member reference type 'struct thermal_zone_device_ops' is not a pointer; did you mean to use '.'?
     3050 |                         tz->ops->set_trip_temp(tz, i, temperature  * MCELSIUS);
          |                         ~~~~~~~^~
          |                                .
    .../soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:3127:11: error: member reference type 'struct thermal_zone_device_ops' is not a pointer; did you mean to use '.'?
     3127 |                         tz->ops->set_trip_temp(tz, 3, temperature  * MCELSIUS);
          |                         ~~~~~~~^~
          |                                .

Update the code here accordingly,

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=698a1eb1f75e
          ("thermal: core: Store zone ops in struct thermal_zone_device")
Test: TH
Bug: 333526538
Change-Id: I95a2cd724518715f29973eaadf6984326d39c3c6
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit 08fc4f10c65ecd0ae8dcf52692b9a5323ab4a209)
Signed-off-by: Will McVicker <willmcvicker@google.com>