input: fingerprint: 'cb_mutex' member removed from 'struct netlink_kernel_cfg' (v6.11 preparation)
Upstream commit [1] removed the 'cb_mutex' member from
'struct netlink_kernel_cfg' causing the OOT pixel driver to fail
compilation:

private/google-modules/soc/gs/drivers/input/fingerprint/netlink.c:82:14: error: no member named 'cb_mutex' in 'struct netlink_kernel_cfg'
   82 |         netlink_cfg.cb_mutex = NULL;
      |         ~~~~~~~~~~~ ^
1 error generated.

There's no user upstream of that lock anymore and the OOT downstream
driver does not use it either, so remove the superfluous initialization.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5fbf57a937f418fe204f9dbb7735e91984f4ee6a [1]
	("net: netlink: remove the cb_mutex "injection" from netlink core")
Test: TH
Bug: 359405127
Change-Id: Ibe1f08b338d5c897c23d310887bf1f9d078be80c
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit 050fc4f68e2eecd170af2460934018e3d4207d27)
Signed-off-by: Will McVicker <willmcvicker@google.com>