media: smfc: stop direct access of struct vb2_queue::num_buffers (v6.10 preparation)
Linux commit [1] has changed scalar struct vb2_queue::num_buffers into
a bitmap: struct vb2_queue::bufs_bitmap

This causes compilation of this driver to fail:

    .../drivers/media/platform/exynos/smfc/smfc-v4l2-ioctls.c:929:30: error: no member named 'num_buffers' in 'struct vb2_queue'
      929 |         for (index = 0; index < vq->num_buffers; index++) {
          |                                 ~~  ^
    1 error generated.

Luckily, Linux also added helper APIs, which when used will handle that
transition transparently for drivers.

This commit switches an open-coded test to using the appropriate Linux
helper API that had been added in commit [2], similar to how other
drivers were updated in the series ending in [3].

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a286b0837e13 [1]
      ("media: core: Add bitmap manage bufs array entries")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=741d0f6b5103 [2]
      ("media: videobuf2: Add helper to get queue number of buffers")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4545ca51dd5b [3]
      ("media: usb: usbtv: Stop direct calls to queue num_buffers field")
Test: TH
Bug: 355371784
Change-Id: I6021a0be5acd35654e4b6cff101867691e425edc
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 46aee22ed60b9397941f57ef52165f5e39119f27)
Signed-off-by: Will McVicker <willmcvicker@google.com>