media: smfc: use vb2_is_busy() instead of open-coding (v6.10 preparation)
Linux commit [1] has changed scalar struct vb2_queue::num_buffers into
a bitmap: struct vb2_queue::bufs_bitmap

This causes compilation of this driver to fail:

    .../drivers/media/platform/exynos/smfc/smfc-v4l2-ioctls.c:736:14: error: no member named 'num_buffers' in 'struct vb2_queue'
      736 |         if (thisvq->num_buffers > 0) {
          |             ~~~~~~  ^
    .../drivers/media/platform/exynos/smfc/smfc-v4l2-ioctls.c:744:15: error: no member named 'num_buffers' in 'struct vb2_queue'
      744 |         if (othervq->num_buffers > 0) { /* REQBUFSed on other vq */
          |             ~~~~~~~  ^

Luckily, Linux also added helper APIs, which when used will handle that
transition transparently for drivers.

This commit switches this open-coded test to using the appropriate
Linux helper API that had been added a long time ago in commit [2].

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a286b0837e13 [1]
      ("media: core: Add bitmap manage bufs array entries")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e23ccc0ad925 [2]
      ("[media] v4l: add videobuf2 Video for Linux 2 driver framework")
Test: TH
Bug: 355371784
Change-Id: I4421ef166047c1d9ad702b21467e96d4a1372e09
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 2aac210e95e5799a02558bf6037fec2b23de83cd)
Signed-off-by: Will McVicker <willmcvicker@google.com>