usb: typec: usb_psy: usb_types is a bitmask now (v6.12 compat)
Linux commit [1] has changed struct power_supply_desc::usb_types from
enum power_supply_usb_type to u32 (and removed struct
power_supply_desc::num_usb_types accordingly).

This causes this driver to fail to compile:
    .../drivers/usb/typec/tcpm/google/usb_psy.c:567:15: error: incompatible pointer to integer conversion initializing 'u32' (aka 'unsigned int') with an expression of type 'enum power_supply_usb_type[4]' [-Wint-conversion]
      567 |         .usb_types = usb_psy_data_types,
          |                      ^~~~~~~~~~~~~~~~~~
    .../drivers/usb/typec/tcpm/google/usb_psy.c:568:3: error: field designator 'num_usb_types' does not refer to any field in type 'const struct power_supply_desc'; did you mean 'usb_types'?
      568 |         .num_usb_types = ARRAY_SIZE(usb_psy_data_types),
          |          ^~~~~~~~~~~~~
          |          usb_types
    .../common/include/linux/power_supply.h:252:6: note: 'usb_types' declared here
      252 |         u32 usb_types;
          |             ^
    2 errors generated.

Update the driver accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=364ea7ccaef9 [1]
      ("power: supply: Change usb_types from an array into a bitmask")
Test: TH
Bug: 369476437
Change-Id: Ibfb13ba36633b37dee6ad67e24c1698baf8b45a6
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>