scsi: ufs: pixel: HCPID & HCMID register names have been fixed (v6.12 compat)
Linux commit [1] has renamed the HCPID & HCMID register names to stand
for what they really are.

This causes this OOT Pixel driver to fail to compile:
    ...drivers/scsi/ufs/ufs-pixel.c:1694:1: error: use of undeclared identifier 'REG_CONTROLLER_DEV_ID'
     1694 | PIXEL_HC_REG_ATTR(hcpid, _CONTROLLER_DEV_ID);
          | ^
    ...drivers/scsi/ufs/ufs-pixel.c:1685:28: note: expanded from macro 'PIXEL_HC_REG_ATTR'
     1685 |         value = ufshcd_readl(hba, REG##_uname);                 \
          |                                   ^
    <scratch space>:71:1: note: expanded from here
       71 | REG_CONTROLLER_DEV_ID
          | ^
    ...drivers/scsi/ufs/ufs-pixel.c:1695:1: error: use of undeclared identifier 'REG_CONTROLLER_PROD_ID'; did you mean 'REG_CONTROLLER_PID'?
     1695 | PIXEL_HC_REG_ATTR(hcmid, _CONTROLLER_PROD_ID);
          | ^
    ...drivers/scsi/ufs/ufs-pixel.c:1685:28: note: expanded from macro 'PIXEL_HC_REG_ATTR'
     1685 |         value = ufshcd_readl(hba, REG##_uname);                 \
          |                                   ^
    <scratch space>:76:1: note: expanded from here
       76 | REG_CONTROLLER_PROD_ID
          | ^
    .../common/include/ufs/ufshci.h:29:2: note: 'REG_CONTROLLER_PID' declared here
       29 |         REG_CONTROLLER_PID                      = 0x10,
          |         ^
    3 errors generated.

Update to use the new name.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b9d104465a6c [1]
      ("scsi: ufs: Prepare to add HCI capabilities sysfs")
Test: TH
Bug: 370454348
Change-Id: Id10fddbe167a2de932950a7ea8139cb2f131dfba
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>