driver: thermal: tmu: const'ify trace_thermal_exynos_allow_max_power() (v6.8 compatibility)
Linux commit [1] has made struct thermal_cooling_device::type a 'const
char' and this causes this OOT pixel driver to fail compilation:
    .../soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:735:12: error: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
      735 |                                                      instance->cdev->type, instance->target);
          |                                                      ^~~~~~~~~~~~~~~~~~~~
    .../soc/gs/include/trace/events/thermal_exynos.h:313:60: note: passing argument to parameter 'cdev_type' here
      313 |         TP_PROTO(const char *tmu_name, bool is_hardlimited, char *cdev_type, unsigned long state),
          |                                                                   ^
    1 error generated.

const'ify trace_thermal_exynos_allow_max_power() to fix the warning.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=57a427c81c32
          ("thermal: core: Use kstrdup_const() during cooling device registration")
Test: TH
Bug: 331377611
Change-Id: I2c94217602f3324ec167062bbbaa4e69a89ba56b
Signed-off-by: André Draszik <draszik@google.com>