cpufreq: exynos-acme: follow renaming of arch_update_thermal_pressure() to arch_update_hw_pressure()
Linux commit [1] has renamed arch_update_thermal_pressure() to
arch_update_hw_pressure() with the following explanation:

    Now that cpufreq provides a pressure value to the scheduler, rename
    arch_update_thermal_pressure into HW pressure to reflect that it
    returns a pressure applied by HW (i.e. with a high frequency
    change) and not always related to thermal mitigation but also
    generated by max current limitation as an example. Such high
    frequency signal needs filtering to be smoothed and provide an
    value that reflects the average available capacity into the
    scheduler time scale.

This breaks compilation of this driver:

    .../drivers/cpufreq/exynos-acme.c:290:3: error: call to undeclared function 'arch_update_thermal_pressure'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      290 |                 arch_update_thermal_pressure(&domain->cpus, new_policy->max);
          |                 ^
    1 error generated.

Update the code accordingly.
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4dbc991714e [1]
      ("sched/cpufreq: Rename arch_update_thermal_pressure() => arch_update_hw_pressure()")
Test: TH
Bug: 353665729
Change-Id: I9777dd48ee12e805db3be9be5f91f63e10b4b059
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit b3c2e99b1cfe84f66726f53ccbebaab07df05c52)
Signed-off-by: Will McVicker <willmcvicker@google.com>