iommu: samsung: address Werror=parentheses (MMU_VADDR_FROM_TLB)
gcc emits the following suggestion:

      CC [M]  samsung-iommu-fault.o
    samsung-iommu-fault.c: In function ‘sysmmu_tlb_compare’:
    samsung-iommu-fault.c:23:49: error: suggest parentheses around arithmetic in operand of ‘|’ [-Werror=parentheses]
       23 | #define MMU_VADDR_FROM_TLB(reg, idx)    (((reg) & 0xFFFFC | (idx) & 0x3) << 12)
          |                                           ~~~~~~^~~~~~~~~
    samsung-iommu-fault.c:23:69: error: suggest parentheses around arithmetic in operand of ‘|’ [-Werror=parentheses]
       23 | #define MMU_VADDR_FROM_TLB(reg, idx)    ((((reg) & 0xFFFFC) | (idx) & 0x3) << 12)
          |                                                               ~~~~~~^~~~~

This makes sense and doing so makes the code easier to read - add them.

Test: TH
Fixes: e7e423c36c11 ("iommu/samsung: separate fault handler")
Fixes: bf497d8e4149 ("iommu/samsung: add TLB and SBB dump when fault occurs")
Fixes: 6c64fd0d9527 ("iommu/samsung: separate fault handler")
Fixes: f711db97e4fc ("iommu/samsung: add TLB and SBB dump when fault occurs")
Bug: 423391571
Change-Id: Ia8d9a777807ff0c107e2e0800bd547c235c21dc3
Signed-off-by: André Draszik <draszik@google.com>