usb: typec: usb_psy: fix printf format
drivers/usb/typec/tcpm/google/usb_psy.c:481:11: error: format specifies type 'unsigned long' but the argument has type 'int' [-Werror,-Wformat]
  480 |                 logbuffer_logk(usb_psy->log, LOGLEVEL_INFO, "Starting alarm with expiry %lu\n",
      |                                                                                         ~~~
      |                                                                                         %d
  481 |                                usb_psy->update_sdp_enum_timeout ?
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  482 |                                         SDP_ENUMERATION_TIMEOUT_MS :
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  483 |                                         SDP_ENUMERATION_TIMEOUT_FIRST_CONNECT_MS);
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/usb_psy.c:695:46: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
  693 |         logbuffer_log(usb->log, "%s: %s:%d %s usb_icl_proto_el: %lu by %s",
      |                                                                 ~~~
      |                                                                 %u
  694 |                       __func__, ret < 0 ? "error" : "success", ret,
  695 |                       vote_result ? "voting" : "clearing", vote.val,
      |                                                            ^~~~~~~~

Fixes: 4ebe69e68eb7 ("usb: typec: usb_psy: Add new sysfs attribute to select sdp alarm timeout")
Fixes: 29a2dd8195b2 ("usb: typec: usb_psy: Implement Dead Battery handling")
Test: TH
Bug: 348164658
Change-Id: Ice2bc53ef3921957c5c865f62f00fb24d0340ea0
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 10360ff3a7a72107e3820baeefab97b549a6a96d)
Signed-off-by: Will McVicker <willmcvicker@google.com>