acpm: power_stats: convert platform driver to use dev_groups (v6.10 preparation)
Upstream commit [1] removed devm_device_add_groups() causing the OOT
pixel driver to fail compilation:

../private/google-modules/soc/gs/drivers/soc/google/acpm/power_stats.c:654:8: error: call to undeclared function 'devm_device_add_groups'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  654 |         ret = devm_device_add_groups(&pdev->dev, power_stats_groups);
      |

Platform drivers have the option to have the platform core create and
remove any needed sysfs attribute files. Take advantage of that.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=971187350602d03c4a27c0783ff412502b95720a [1]
	("driver core: remove devm_device_add_groups()")
Test: TH
Bug: 355395075
Change-Id: I24b3756f5911dd8b9046e51fdf91ec4730f61465
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit 81c3eec377790afae9972a9a0cf0c69a3951e77d)
Signed-off-by: Will McVicker <willmcvicker@google.com>