dma-buf: heaps: page_pool: convert to shrinker_register() (v6.7 compatibility)
Linux commit [1] has removed some old shrinker APIs and this causes
this OOT pixel driver to fail compilation:

    .../gs/drivers/dma-buf/heaps/page_pool.c:291:9: error: call to undeclared function 'register_shrinker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            return register_shrinker(&pool_shrinker, "dmabuf-page-pool-shrinker");
                   ^
    .../gs/drivers/dma-buf/heaps/page_pool.c:291:9: note: did you mean 'register_chrdev'?
    .../common/include/linux/fs.h:2604:19: note: 'register_chrdev' declared here
    static inline int register_chrdev(unsigned int major, const char *name,
                      ^
    1 error generated.

Update the driver accordingly.

While at it, correctly mark the module init function with __init.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f2383e01507e
    ("mm: shrinker: remove old APIs")

Bug: 316904748
Test: TH
Change-Id: I8be4ae880319d9ac2aee96e97cfd819e213e3432
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 5cdb6f3781a29d9c9e123104922673d289ed97c5)