treewide: remove I2C_CLASS_SPD (v6.10 preparation)
Upstream commit [1] removed I2C_CLASS_SPD causing some OOT pixel drivers
to fail compilation:

../private/google-modules/soc/gs/drivers/i2c/busses/i2c-acpm.c:70:49: error: use of undeclared identifier 'I2C_CLASS_SPD'
   70 |         acpm_mfd_bus->adap.class   = I2C_CLASS_HWMON | I2C_CLASS_SPD;
      |                                                        ^
1 error generated.

../private/google-modules/soc/gs/drivers/i2c/busses/i2c-exynos5.c:1229:40: error: use of undeclared identifier 'I2C_CLASS_SPD'
 1229 |         i2c->adap.class   = I2C_CLASS_HWMON | I2C_CLASS_SPD;
      |                                               ^
1 error generated.

According to the upstream commit [2], for i2c client drivers that
also support I2C_CLASS_HWMON, the i2c adapters don't have to declare
support for I2C_CLASS_SPD if they support I2C_CLASS_HWMON. Since all the
i2c adapter drivers from dowsntream support I2C_CLASS_HWMON, and there
is no i2c client driver downstream that declares I2C_CLASS_SPD, follow
upstream and remove I2C_CLASS_SPD from the i2c adapters.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e61bcf42d290e73025bab38e0e55a5586c2d8ad5 [1]
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9fd12f385720a85b4ce9a3cb98e66d470a5efd20 [2]
Test: TH
Bug: 355391883
Change-Id: I3e211bd80586022e56a36d9faee8cda4db7a7df3
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit 4ec02fd0d5ebf8ae36403ca66eeaa4e733ca926e)
Signed-off-by: Will McVicker <willmcvicker@google.com>