usb: typec: tcpci_max77759: tcpm_pd_receive() update (v6.9 compatibility)
Linux commit [1] has const'ified struct iommu_ops::of_xlate(). This
causes compilation of this OOT Pixel driver to fail:

    .../soc/gs/drivers/usb/typec/tcpm/google/tcpci_max77759.c:747:34: error: too few arguments to function call, expected 3, have 2
      747 |         tcpm_pd_receive(chip->port, &msg);
          |         ~~~~~~~~~~~~~~~                 ^
    .../common/include/linux/usb/tcpm.h:183:6: note: 'tcpm_pd_receive' declared here
      183 | void tcpm_pd_receive(struct tcpm_port *port,
          |      ^               ~~~~~~~~~~~~~~~~~~~~~~~
      184 |                      const struct pd_message *msg,
          |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      185 |                      enum tcpm_transmit_type rx_sop_type);
          |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Update the code accordingly.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3bbb9ba4f660
          ("usb: typec: tcpci: add tcpm_transmit_type to tcpm_pd_receive")
Bug: 333518435
Test: TH
Change-Id: If5901b7f196cb62b01e39d1cb162780cf4a84c73
Signed-off-by: André Draszik <andre.draszik@linaro.org>
(cherry picked from commit 92374f30680f98e791a15e2965cdb7ec18f4d3bd)
Signed-off-by: Will McVicker <willmcvicker@google.com>