soc/google: debug-snapshot: s/flush_cache_all/dbg_snapshot_flush_cache_all (v6.9 compatibility)
On the way to v6.9 the following compilation error was revealed
downstream:

common/include/asm-generic/cacheflush.h:17:20: error: static declaration of 'flush_cache_all' follows non-static declaration
   17 | static inline void flush_cache_all(void)
      |                    ^
common/../private/google-modules/soc/gs/drivers/soc/google/debug/debug-snapshot-local.h:95:13: note: previous declaration is here
   95 | extern void flush_cache_all(void);
      |             ^

For whatever reason debug-snapshot chose to implement its own
flush_cache_all() method. Since it's not generic, prepend
```dbg_snapshot_``` to the method name. Apart of the debug-snapshot
driver, there's another pixel driver that's using flush_cache_all():
dbgcore-dump, but that is using the empty method defined in
<asm/cacheflush.h>.

Test: TH
Bug: 335568429
Change-Id: I2a163d9579136c92fbbb6143432f97ffc4f31d35
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit 5ae271a061a996e0500eaba13432d03bcfa80908)
Signed-off-by: Will McVicker <willmcvicker@google.com>