driver: devfreq: arm_memlat_mon: replace of_device.h with excplicit includes (v6.8 compatibility)
Linux commit [1] has removed some old, long-standing circular includes
in of_device.h and of_platform.h which causes this OOT pixel driver to
fail compilation:
    .../soc/gs/drivers/devfreq/google/arm-memlat-mon.c:883:4: error: call to undeclared function 'of_platform_populate'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      883 |                         of_platform_populate(dev->of_node, NULL, NULL, dev);
          |                         ^
    1 error generated.

The DT of_device.h and of_platform.h date back to the separate
of_platform_bus_type before it as merged into the regular platform bus.
As part of that merge prepping Arm DT support 13 years ago, they
"temporarily" include each other. They also include platform_device.h
and of.h.

of_device.h isn't needed, but of_platform.h and mod_devicetable.h were
implicitly included. Make them explicit.

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ef175b29a242
          ("of: Stop circularly including of_device.h and of_platform.h")
Test: TH
Bug: 331381449
Change-Id: I8b973b40990c516fae276ef78b73198220e5d463
Signed-off-by: André Draszik <draszik@google.com>