watchdog: s3c2410_wdt: don't use max() where a C constant expression is wanted (v6.11 compatibility)
Linux commit [1] changes max() to not result in a C constant
expression, making it impossible to use here, as the compiler then
complains about variable length arrays:

    .../drivers/watchdog/s3c2410_wdt.c:692:11: error: variable length array used [-Werror,-Wvla]
      692 |         char buf[max(NR_CPUS, PRINT_CPUS_LIMIT)];
          |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For cases like this, the generic MAX() macro was introduced with the
traditional semantics in [2].

Similar to Linux commit [3], use MAX() instead.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dc1c8034e31b [1]
      ("minmax: simplify min()/max()/clamp() implementation")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1a251f52cfdc [2]
      ("minmax: make generic MIN() and MAX() macros available everywhere")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cb04e8b1d2f2 [3]
      (""minmax: don't use max() in situations that want a C constant expression)
Test: TH
Bug: 363180616
Change-Id: Ia23c5266a27d81e094b034d875fade3b6cfc1e62
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 548bd2b1a3ad2a32d4e0e95300da9ce6e05dd595)
Signed-off-by: Will McVicker <willmcvicker@google.com>