pixel_em: struct em_perf_domain::table is gone (v6.9 compatibility)
Linux commit [1] and parents have added runtime modification support of
the EM. Due to interface changes, in particular 2, this breaks
compilation of the OOT Pixel EM driver:

    .../soc/gs/drivers/soc/google/vh/kernel/pixel_em/pixel_em.c:489:31: error: no member named 'table' in 'struct em_perf_domain'
      489 |         unsigned long max_freq = pd->table[max_freq_index].frequency;
          |                                  ~~  ^
    ...
    .../soc/gs/drivers/soc/google/vh/kernel/pixel_em/pixel_em.c:508:32: error: no member named 'table' in 'struct em_perf_domain'
      508 |                 dst->opps[opp_id].cost = pd->table[opp_id].cost;
          |                                          ~~  ^
    ...

Update the driver as per upstream changes.

Maybe one day we can get rid of the vendor hook...

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3bd834640baa
          ("Merge branch 'pm-em'")
Link: [2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=24e9fb635df2
          ("PM: EM: Remove old table")
Test: TH
Bug: 333732178
Change-Id: Ib5f9e30ecfab27d20db243581108b37daadffa18
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit e28250cdb146d7845ee0667099caa2147deb280c)
Signed-off-by: Will McVicker <willmcvicker@google.com>