tcpci_max77759: fix missing prototypes and reenable -Wmissing-prototypes
Deal with all the missing prototypes in ths max77759 TypeC driver:
    .../drivers/usb/typec/tcpm/google/bc_max77759.c:199:6: error: no previous prototype for function 'clear_chg_typ' [-Werror,-Wmissing-prototypes]
      199 | void clear_chg_typ(struct bc12_status *bc12)
          |      ^

    .../drivers/usb/typec/tcpm/google/max77759_helper.c:47:5: error: no previous prototype for function 'max77759_read16' [-Werror,-Wmissing-prototypes]
       47 | int max77759_read16(struct regmap *regmap, unsigned int reg,
          |     ^
    .../drivers/usb/typec/tcpm/google/max77759_helper.c:54:5: error: no previous prototype for function 'max77759_write16' [-Werror,-Wmissing-prototypes]
       54 | int max77759_write16(struct regmap *regmap, unsigned int reg,
          |     ^
    .../drivers/usb/typec/tcpm/google/max77759_helper.c:61:5: error: no previous prototype for function 'max77759_read8' [-Werror,-Wmissing-prototypes]
       61 | int max77759_read8(struct regmap *regmap, unsigned int reg,
          |     ^
    .../drivers/usb/typec/tcpm/google/max77759_helper.c:68:5: error: no previous prototype for function 'max77759_write8' [-Werror,-Wmissing-prototypes]
       68 | int max77759_write8(struct regmap *regmap, unsigned int reg,
          |     ^
    .../drivers/usb/typec/tcpm/google/max77759_helper.c:75:5: error: no previous prototype for function 'max77759_update_bits16' [-Werror,-Wmissing-prototypes]
       75 | int max77759_update_bits16(struct regmap *regmap, unsigned int reg, u16 mask,
          |     ^
    .../drivers/usb/typec/tcpm/google/max77759_helper.c:82:5: error: no previous prototype for function 'max77759_update_bits8' [-Werror,-Wmissing-prototypes]
       82 | int max77759_update_bits8(struct regmap *regmap, unsigned int reg, u8 mask,
          |     ^

    .../drivers/usb/typec/tcpm/google/tcpci_max77759.c:751:38: error: no previous prototype for function 'init_compliance_warnings' [-Werror,-Wmissing-prototypes]
      751 | struct max77759_compliance_warnings *init_compliance_warnings(struct max77759_plat *chip)
          |                                      ^
    .../drivers/usb/typec/tcpm/google/tcpci_max77759.c:1074:6: error: no previous prototype for function 'disconnect_missing_rp_partner' [-Werror,-Wmissing-prototypes]
     1074 | void disconnect_missing_rp_partner(struct max77759_plat *chip)
          |      ^
    .../drivers/usb/typec/tcpm/google/tcpci_max77759.c:2217:6: error: no previous prototype for function 'max77759_bc12_is_running' [-Werror,-Wmissing-prototypes]
     2217 | void max77759_bc12_is_running(struct max77759_plat *chip, bool running)
          |      ^

Some notes:
* clear_chg_typ() appears completely unused anywhere in the Pixel driver
  sources, so it's being fully removed
* missing prototypes in max77759_helper.c are all declared in the
  relevant header
* symbols referenced in tcpci_max77759.c are all local APIs and don't
  appear to be used elsewhere.

Bug: 330718746
Test: TH
Change-Id: Idd689c3813a58e1d291210f442f461ef923fd0b3
Signed-off-by: André Draszik <andre.draszik@linaro.org>