phy: const'ify of_phandle_args in of_xlate() (v6.9 compatibility)
Linux commit [1] has const'ified struct phy_provider::of_xlate(). This
causes compilation of OOT Pixel PHY drivers to fail:

    .../soc/gs/drivers/phy/samsung/phy-exynos-mipi-dsim.c:383:17: error: incompatible function pointer types passing 'struct phy *(struct device *, struct of_phandle_args *)' to parameter of type 'struct phy *(*)(struct device *, const struct of_phandle_args *)' [-Wincompatible-function-pointer-types]
      383 |         phy_provider = devm_of_phy_provider_register(dev,
          |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      384 |                         exynos_mipi_phy_of_xlate);
          |                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    .../common/include/linux/phy/phy.h:207:60: note: expanded from macro 'devm_of_phy_provider_register'
      207 |         __devm_of_phy_provider_register((dev), NULL, THIS_MODULE, (xlate))
          |                                                                   ^~~~~~~
    .../common/include/linux/phy/phy.h:288:17: note: passing argument to parameter 'of_xlate' here
      288 |         struct phy * (*of_xlate)(struct device *dev,
          |                        ^

Update the code here accordingly,

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=00ca8a15dafa
          ("phy: constify of_phandle_args in xlate")
Test: TH
Bug: 333507994
Change-Id: I57beac746a4ec6ef6b24c1a3680413360bcd17dd
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 8eb2a09cc4eb84f126dcd9742fcae37d335782c5)
Signed-off-by: Will McVicker <willmcvicker@google.com>