drivers: themal: tmu: struct thermal_zone_device::trips changed type (v6.10 compatibility)
Linux commit [1] has changed struct thermal_zone_device::trips from
struct thermal_trip to struct thermal_trip_desc. This causes
compilation of this driver to fail:

    .../drivers/thermal/samsung/gs_tmu_v2.c:716:29: error: incompatible pointer types initializing 'const struct thermal_trip *' with an expression of type 'struct thermal_trip_desc *' [-Werror,-Wincompatible-pointer-types]
      716 |         const struct thermal_trip *control_temp_trip
          |                                    ^
      717 |                 = &tz->trips[data->pi_param->trip_control_temp];
          |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/thermal/samsung/gs_tmu_v2.c:814:29: error: incompatible pointer types initializing 'const struct thermal_trip *' with an expression of type 'struct thermal_trip_desc *' [-Werror,-Wincompatible-pointer-types]
      814 |         const struct thermal_trip *control_temp_trip
          |                                    ^
      815 |                 = &tz->trips[params->trip_control_temp];
          |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

Update the code here accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=daeeb032f42d [1]
      ("thermal: core: Move threshold out of struct thermal_trip")
Test: TH
Bug: 353936817
Change-Id: I7822460f1eb412ddb3a1553fdacf503cc94f3735
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 338cab07e648971f09db9a747fb3fe437556c8de)
Signed-off-by: Will McVicker <willmcvicker@google.com>