drivers: thermal: tmu: follow v6.7 struct thermal_instance API change
Linux commit [1] has changed struct thermal_instance which now contains
a struct thermal_trip pointer instead of a trip index.

This causes OOT pixel drivers to fail compilation:

.../private/google-modules/soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:722:22: error: comparison between pointer and integer ('const struct thermal_trip *' and 'int') [-Werror,-Wpointer-integer-compare]
                if (instance->trip != control_temp ||
                    ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
.../private/google-modules/soc/gs/drivers/thermal/samsung/gs_tmu_v2.c:825:22: error: comparison between pointer and integer ('const struct thermal_trip *' and 'int') [-Werror,-Wpointer-integer-compare]
                if (instance->trip == params->trip_control_temp &&
                    ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~

Just follow the same changes here.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2c7b4bfadef0
    ("thermal: core: Store trip pointer in struct thermal_instance")

Fixes: 2c7b4bfadef0 ("thermal: core: Store trip pointer in struct thermal_instance")
Test: TH
Bug: 314092273
Change-Id: I4c3d44f911d9d55891570aea0b624c43287001af
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 25c1e9e51f0e96656919ea397a391b32d6b91a72)