tty: serial: exynos_tty: switch from circ_buf to kfifo (v6.10 compatibility)
Linux commit [1] has converted serial drivers to using kfifo instead of
circ_buf.

This causes compilation of this driver to fail:

    .../drivers/tty/serial/exynos_tty.c:666:40: error: no member named 'xmit' in 'struct uart_state'
      666 |         struct circ_buf *xmit = &port->state->xmit;
          |                                  ~~~~~~~~~~~  ^
    .../drivers/tty/serial/exynos_tty.c:687:7: error: incomplete definition of type 'struct circ_buf'
      687 |                 xmit->tail = (xmit->tail + count) & (UART_XMIT_SIZE - 1);
          |                 ~~~~^
    .../drivers/tty/serial/exynos_tty.c:666:9: note: forward declaration of 'struct circ_buf'
      666 |         struct circ_buf *xmit = &port->state->xmit;
          |                ^
    .../drivers/tty/serial/exynos_tty.c:687:21: error: incomplete definition of type 'struct circ_buf'
      687 |                 xmit->tail = (xmit->tail + count) & (UART_XMIT_SIZE - 1);
          |                               ~~~~^
    .../drivers/tty/serial/exynos_tty.c:666:9: note: forward declaration of 'struct circ_buf'
      666 |         struct circ_buf *xmit = &port->state->xmit;
          |                ^
    .../drivers/tty/serial/exynos_tty.c:706:40: error: no member named 'xmit' in 'struct uart_state'
      706 |         struct circ_buf *xmit = &port->state->xmit;
          |                                  ~~~~~~~~~~~  ^
    .../drivers/tty/serial/exynos_tty.c:721:6: error: incomplete definition of type 'struct circ_buf'
      721 |         xmit->tail = (xmit->tail + count) & (UART_XMIT_SIZE - 1);
          |         ~~~~^
    .../drivers/tty/serial/exynos_tty.c:706:9: note: forward declaration of 'struct circ_buf'
      706 |         struct circ_buf *xmit = &port->state->xmit;
          |                ^
    .../drivers/tty/serial/exynos_tty.c:721:20: error: incomplete definition of type 'struct circ_buf'
      721 |         xmit->tail = (xmit->tail + count) & (UART_XMIT_SIZE - 1);
          |                       ~~~~^
    etc.

Do the same conversion to this driver.

Some notes:

Unlike the upstream version, we're keeping the 'count > 0' exit
condition in exynos_serial_tx_chars() for two reasons:

* 'trace_buf[]' has space for at most 'count' bytes and we don't want
  to end up with an out-of-bounds write
* we otherwise never get to do the DMA version of the transfer via the
  test just below: 'if (!count && dma_count)'
  exynos_serial_start_tx_dma(). While untested (we don't use DMA at the
  moment, due to the DT), this seems more correct.

The side-effect is that if DMA is disabled, we only ever write a
maximum of 'count' (i.e. port->fifosize) bytes per invocation, but that
difference should be neglegible.

As preparatory patch for this conversion, upstream also changed some
drivers to use dmaengine_prep_slave_sg() instead of
dmaengine_prep_slave_single(), e.g. msm_serial.c in commit [2], because
'kfifo understands only scatter-gatter approach'. For some reason
upstream didn't change samsung_tty, and we don't use DMA in this tree,
so I've left out the dmaengine_prep_slave_single() conversion from this
driver as well.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1788cf6a91d9 [1]
      ("tty: serial: switch from circ_buf to kfifo")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f8fef2fa419f [2]
      ("tty: msm_serial: use dmaengine_prep_slave_sg()")
Test: TH
Bug: 355424475
Change-Id: I864b4cacbc131d3e412c9b425a610ee408144169
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 595d38e82cc02f857cded10c21cf098c9b9ea446)
Signed-off-by: Will McVicker <willmcvicker@google.com>