soc: google: acpm: kstat_irqs is a struct now (v6.10 compatibility)
Linux commit [1] has changed struct irq_desc::kstat_irqs from unsigned
int to struct irqstat.

This breaks compilation of this driver:

    .../drivers/soc/google/acpm/acpm_ipc.c:639:12: error: incompatible pointer to integer conversion assigning to 'unsigned int' from 'typeof (*((&(desc->kstat_irqs))))' (aka 'struct irqstat *') [-Wint-conversion]
      639 |                         irq_cnt += per_cpu(desc->kstat_irqs, cpu);
          |                                 ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Update the code accordingly.

Note that there also is some code in here to gather interrupt
statistics (see retry argument in this cpu_irq_info_dump() and the
caller __acpm_ipc_send_data(). Commits specifically for doing such a
thing [2] [3] [4] [5], adding a new API have also been added to Linux
subsequently. We should look into using those instead of the
hand-rolled approach (as a follow-up change).

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=86d2a2f51fba [1]
       ("genirq: Convert kstat_irqs to a struct")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=99cf63c56661 [2]
      ("genirq: Provide a snapshot mechanism for interrupt statistics")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=25a4a0151180 [3]
      ("genirq: Avoid summation loops for /proc/interrupts")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d7037381d002 [4]
      ("watchdog/softlockup: Low-overhead detection of interrupt storm")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e9a9292e2368 [5]
      ("watchdog/softlockup: Low-overhead detection of interrupt storm")
Test: TH
Bug: 353704691
Change-Id: I4af3def03fd30ba5a5cad031648c93a9ff8e697a
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit c4d8b1a9546e07b58f3162d36b14e34f694957ab)
Signed-off-by: Will McVicker <willmcvicker@google.com>