soc: gs-chipid: fix missing prototypes and reenable -Wmissing-prototypes
gcc correctly complains:
    drivers/soc/google/gs-chipid.c:290:5: error: no previous declaration for ‘gs_chipid_get_type’ [-Werror=missing-declarations]
      290 | u32 gs_chipid_get_type(void)
          |     ^~~~~~~~~~~~~~~~~~
    drivers/soc/google/gs-chipid.c:299:5: error: no previous declaration for ‘gs_chipid_get_dvfs_version’ [-Werror=missing-declarations]
      299 | s32 gs_chipid_get_dvfs_version(void)
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/soc/google/gs-chipid.c:308:5: error: no previous declaration for ‘gs_chipid_get_revision’ [-Werror=missing-declarations]
      308 | u32 gs_chipid_get_revision(void)
          |     ^~~~~~~~~~~~~~~~~~~~~~
    drivers/soc/google/gs-chipid.c:317:5: error: no previous declaration for ‘gs_chipid_get_product_id’ [-Werror=missing-declarations]
      317 | u32 gs_chipid_get_product_id(void)
          |     ^~~~~~~~~~~~~~~~~~~~~~~~
    drivers/soc/google/gs-chipid.c:424:5: error: no previous declaration for ‘gs_chipid_get_ap_hw_tune_array’ [-Werror=missing-declarations]
      424 | int gs_chipid_get_ap_hw_tune_array(const u8 **array)
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/soc/google/gs-chipid.c:479:6: error: no previous declaration for ‘gs_chipid_early_init’ [-Werror=missing-declarations]
      479 | void gs_chipid_early_init(void)
          |      ^~~~~~~~~~~~~~~~~~~~

Add the prototypes to a specific header, which also allows users to not
have to add their own forward declarations.

Test: TH
Bug: 424610699
Change-Id: I9d11bca25d46e4ec7298568ca029be649fb2cefd
Signed-off-by: André Draszik <draszik@google.com>