pci: pcie-exynos-rc: fix section mismatch error (v6.11 compatibility)
WARNING: modpost: ../private/google-modules/soc/gs/drivers/pci/controller/dwc/pcie-exynos-gs:
 section mismatch in reference: exynos_pcie_rc_driver+0x8 (section: .data) -> exynos_pcie_rc_remove (section: .exit.text)

ERROR: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.

Make section match.

Test: TH
Bug: 361730773
Change-Id: I9040a2c5d71677af538f80a7d6cf937bd3ca15ca
Signed-off-by: Peter Griffin <gpeter@google.com>
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit a998f12a04575061e188b02818cacd286b87364e)
Signed-off-by: Will McVicker <willmcvicker@google.com>