tty: serial: exynos_tty: fix trivial -Wswitch error
Upstream commit 1404d3509c76 ("serial: switch uart_port::iotype to enum
uart_iotype") moved the UPIO_* defines into a new 'enum uart_tiotype'.
This causes a trivial -Wswitch build issue in exynos_tty driver:

  ../drivers/tty/serial/exynos_tty.c:218:10:
  error: 7 enumeration values not handled in switch: 'UPIO_UNKNOWN', 'UPIO_PORT', 'UPIO_HUB6'... [-Werror,-Wswitch]
    218 |         switch (port->iotype) {
        |                 ^~~~~~~~~~~~

Fix it by explicitly ignoring the remaining enums via default case.

Link: https://git.kernel.org/torvalds/c/1404d3509c76
Change-Id: I3a749fbfe7aa40608f6db5254f347720463cd8b9
Signed-off-by: Carlos Llamas <cmllamas@google.com>