i2c: update .probe() for v6.3 kernel (s2mpg1[23]-core.c)
Upstream kernel commit [1] has switched probe() to the same
signature as probe_new(), which breaks compilation for the
drivers here:
.../drivers/mfd/s2mpg13-core.c:433:11: error: incompatible function pointer types initializing 'int (*)(struct i2c_client *)' with an expression of type 'int (struct i2c_client *, const struct i2c_device_id *)' [-Wincompatible-function-pointer-types]
  433 |         .probe = s2mpg13_i2c_probe,
      |                  ^~~~~~~~~~~~~~~~~
.../drivers/mfd/s2mpg12-core.c:584:11: error: incompatible function pointer types initializing 'int (*)(struct i2c_client *)' with an expression of type 'int (struct i2c_client *, const struct i2c_device_id *)' [-Wincompatible-function-pointer-types]
  584 |         .probe = s2mpg12_i2c_probe,
      |                  ^~~~~~~~~~~~~~~~~

The probe function doesn't make use of the i2c_device_id * parameter so
it can be trivially converted.

This is similar to commit 3444929bbd37 ("i2c: convert to struct
i2c_driver::probe_new() (prepare for v6.3 kernel)") and
commit a31706be71ac ("i2c: switch back to use struct i2c_driver's
.probe() (prepare for v6.6 kernel)") in this repository for the other
i2c drivers.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=03c835f498b5
    ("i2c: Switch .probe() to not take an id parameter")

Bug: 277308451
Bug: 307735139
Test: compiles
Change-Id: I08352f6fa42afc18a0ba081dcd8e0a66719f99ad
Signed-off-by: André Draszik <draszik@google.com>