thermal: gs101_spmic_thermal: update .set_trip_temp() parameters (v6.11 compatibility)
Upstream commit [1] modified trip_point_temp_store() to pass a (const)
trip pointer to .set_trip_temp() causing the downstream pixel driver to
fail compilation:

drivers/thermal/google/gs101_spmic_thermal.c:316:19: error: incompatible function pointer types initializing 'int (*)(struct thermal_zone_device *, const struct thermal_trip *, int)' with an expression of type 'int (struct thermal_zone_device *, int, int)' [-Wincompatible-function-pointer-types]
  316 |         .set_trip_temp = gs101_spmic_thermal_set_trip_temp,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Drivers invoking __thermal_zone_get_trip() from their .set_trip_temp()
callback functions do not need to invoke it anymore because they
receive the trip point as a function argument. Update the code
accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0728c810873e1a94e8b767f9809af940c9307d60 [1]
Fixes: 0728c810873e ("thermal: trip: Pass trip pointer to .set_trip_temp() thermal zone callback")
Test: TH
Bug: 358330128
Change-Id: I6791d22eb1171019a7891e01d90679fdd9f7540e
Signed-off-by: Tudor Ambarus <tudordana@google.com>
(cherry picked from commit b99fd2c58744b951ea33cf974d9b2db5744b97bb)
Signed-off-by: Will McVicker <willmcvicker@google.com>