scsi: ufs: exynos: move setting the DMA alignment to the init method (v6.10 compatibility)
The series ending in Linux commit [1] has cleaned up the block/scsi
layer a little. Drivers are not required or expected to call the block
layer DMA alignment limits helpers themselves. Commit [2] enforces this
for UFS-Exynos - struct ufs_hba_variant_ops::config_scsi_dev is gone,
as is blk_queue_update_dma_alignment().

This causes compilation of this driver to fail:

    .../private/google-modules/soc/gs/drivers/scsi/ufs/ufs-exynos.c:968:2: error: call to undeclared function 'blk_queue_update_dma_alignment'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      968 |         blk_queue_update_dma_alignment(sdev->request_queue, SZ_4K - 1);
          |         ^
    .../private/google-modules/soc/gs/drivers/scsi/ufs/ufs-exynos.c:968:2: note: did you mean 'blk_queue_update_dma_pad'?
    .../common/include/linux/blkdev.h:941:13: note: 'blk_queue_update_dma_pad' declared here
      941 | extern void blk_queue_update_dma_pad(struct request_queue *, unsigned int);
          |             ^
    .../private/google-modules/soc/gs/drivers/scsi/ufs/ufs-exynos.c:986:3: error: field designator 'config_scsi_dev' does not refer to any field in type 'struct ufs_hba_variant_ops'
      986 |         .config_scsi_dev = __exynos_ufs_config_scsi_dev,
          |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

Update the driver with a similar patch as upstream did in [2].

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ec84ca4025c0 [1]
      ("scsi: block: Remove now unused queue limits helpers")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=67144d3c58b4 [2]
      ("scsi: ufs: ufs-exynos: Move setting the the DMA alignment to the init method")
Test: TH
Bug: 353958104
Change-Id: Id164352d6de337bd6455b79b3354a9db7c925598
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit dd61bb68aa3910400244f037000bb47f587eca86)
Signed-off-by: Will McVicker <willmcvicker@google.com>