google/debug: kstat_irqs is a struct now (v6.10 compatibility)
Linux commit [1] has changed struct irq_desc::kstat_irqs from unsigned
int to struct irqstat.

This breaks compilation of this driver:

    .../drivers/soc/google/debug/debug-snapshot-log.c:684:13: error: invalid operands to binary expression ('unsigned int' and 'typeof (*((desc->kstat_irqs)))' (aka 'struct irqstat'))
      684 |                         irq_stat += *per_cpu_ptr(desc->kstat_irqs, cpu);
          |                         ~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Update the code accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=86d2a2f51fba [1]
       ("genirq: Convert kstat_irqs to a struct")
Test: TH
Bug: 353704691
Change-Id: Id881546115fcf5f604f0a47efb4594d5aabbcfa1
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit a2533d2320d7026c9008b0bbb556d2b141c448ff)
Signed-off-by: Will McVicker <willmcvicker@google.com>